
spring:
  application:
      name: webflux
#  profiles:
#    active: dev



server:
  port: 10008
  servlet:
    context-path: /
  address: localhost



logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    com:
      kq: DEBUG

